name: vcpkg-install-harfbuzz

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  VCPKG_ROOT: "c:/Program Files/vcpkg"
  VCPKG_BINARY_SOURCES: clear;nuget,GitHub,read;nugettimeout,3600

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: read

    steps:
    - name: Setup NuGet
      shell: pwsh
      run: |
        nuget sources add `
          -source "https://nuget.pkg.github.com/PurpleFlowerGarden/index.json" `
          -storepasswordincleartext `
          -name "GitHub" `
          -username "${{ github.repository_owner }}" `
          -password "${{ secrets.GITHUB_TOKEN }}"
        nuget setapikey `
          "${{ secrets.GITHUB_TOKEN }}" `
          -source "GitHub"
        nuget sources

    - name: Checkout VCPKG
      shell: pwsh
      run:  git clone https://github.com/microsoft/vcpkg.git "${env:VCPKG_ROOT}"

    - name: Bootstrap VCPKG
      shell: pwsh
      run: |
        cd "${env:VCPKG_ROOT}"
        ./bootstrap-vcpkg.bat

    - name: Provision harfbuzz
      shell: pwsh
      run: |
        cd "${env:VCPKG_ROOT}"
        ./vcpkg install --debug --editable harfbuzz:x64-windows

    - name: Archive VCPKG Log Files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: buildlogs
        path: |
          ${{ env.VCPKG_ROOT }}/buildtrees/*/*.txt
          ${{ env.VCPKG_ROOT }}/buildtrees/*/*.log
